[workspace]
members = [
	"cedar-policy",
	"cedar-policy-core",
	"cedar-policy-validator",
	"cedar-policy-formatter",
	"cedar-policy-cli",
	"cedar-db-example"
]

# Enable global integer overflow detection for the release profile
[profile.release]
overflow-checks = true



